"""empty message

Revision ID: 825eb6f1fc3b
Revises: b7786fe23a24
Create Date: 2020-01-10 18:58:07.570832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825eb6f1fc3b'
down_revision = 'b7786fe23a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
